apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cource3/argocd/argocd-demo/python-manifests
    repoURL: https://github.com/haco1123/udacityTraining 
    targetRevision: HEAD
  syncPolicy: {}
