namespace:
  name: sandbox
 
image:
  repository: leon494/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    memory: "128Mi"
    cpu: "500m"

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

containerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz
 
replicaCount: 1
