## provide the name of the namespace
namespace:
  name: demo

## define the image to execute with the Deployment 
image:
  repository: nginx 
  tag: alpine
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 256Mi

service:
  port: 8111
  type: ClusterIP

configmap:
  data: "version: alpine"

## set the number of replicas for an application 
replicaCount: 3
