## provide the name of the namespace
namespace:
  name: staging

## define the image to execute with the Deployment 
image:
  repository: nginx 
  tag: 1.18.0
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 128Mi

service:
  port: 8111
  type: ClusterIP

configmap:
  data: "version: 1.18.0"

## set the number of replicas for an application 
replicaCount: 1
